site_name: "Bridge2AI Standards Registry"
theme:
  name: material
  font:
    text: Inter
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.tabs.link
    - toc.integrate
plugins:
  - search
nav:
  - Index: index.md
  - Standards: DataStandardOrTool.markdown
  - Use Cases: UseCase.markdown
  - Substrates: DataSubstrate.markdown
  - Topics: DataTopic.markdown
  - Organizations: Organization.markdown
site_url: https://bridge2ai.github.io/b2ai-standards-registry
repo_url: https://github.com/bridge2ai/b2ai-standards-registry
markdown_extensions:
  - tables
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bridge2ai/b2ai-standards-registry
      name: Standards Registry GitHub
